sudo pip3 install pexpect
sudo chmod 755 /usr/local/lib/python3.4/dist-packages/pexpect/
sudo chmod 644 /usr/local/lib/python3.4/dist-packages/pexpect/*.py
sudo chmod 755 /usr/local/lib/python3.4/dist-packages/pexpect-4.2.1.dist-info/
sudo chmod 644 /usr/local/lib/python3.4/dist-packages/pexpect-4.2.1.dist-info/*
sudo chmod 755 /usr/local/lib/python3.4/dist-packages/ptyprocess/
sudo chmod 644 /usr/local/lib/python3.4/dist-packages/ptyprocess/*.py
sudo chmod 755 /usr/local/lib/python3.4/dist-packages/ptyprocess-0.5.1.dist-info/
sudo chmod 644 /usr/local/lib/python3.4/dist-packages/ptyprocess-0.5.1.dist-info/*